export const DELETE_USER = 'DELETE_USER';
export const SAVE_USER = 'SAVE_USER';
export const GET_USERS = 'GET_USERS';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_OUT = 'LOGIN_USER_OUT';
export const USER_LOADING = 'USER_LOADING';
export const USER_LOADING_OFF = 'USER_LOADING_OFF';
export const SET_PAYLOAD = 'SET_PAYLOAD';
export const UPDATE_USER = 'UPDATE_USER';
export const BLOQUEAR_USER = 'BLOQUEAR_USER';
export const DESBLOQUEAR_USER = 'DESBLOQUEAR_USER';

export const DELETE_USER_HUELLA = 'DELETE_USER_HUELLA';
export const GET_USERS_HUELLAS = 'GET_USERS_HUELLAS';
export const HUELLA_LOADING = 'HUELLA_LOADING';
export const HUELLA_LOADING_OFF = 'HUELLA_LOADING_OFF';

export const DELETE_TIENDA = 'DELETE_TIENDA';
export const SAVE_TIENDA = 'SAVE_TIENDA';
export const GET_TIENDAS = 'GET_TIENDAS';
export const TIENDA_LOADING = 'TIENDA_LOADING';
export const TIENDA_LOADING_OFF = 'TIENDA_LOADING_OFF';
export const UPDATE_TIENDA = 'UPDATE_TIENDA';

export const GET_ASISTENCIAS = 'GET_ASISTENCIAS';
export const GET_ASISTENCIAS_TIENDA = 'GET_ASISTENCIAS_TIENDA';

export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';
export const SET_MESSAGE = 'SET_MESSAGE';
 